import markdown
from pathlib import Path

def md_to_html(md_path, html_path):
    """Convert Markdown to styled HTML (ready for browser PDF print)."""
    
    # Read markdown
    with open(md_path, 'r', encoding='utf-8') as f:
        md_content = f.read()
    
    # Convert to HTML
    html_body = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])
    
    # Professional academic paper styling
    styled_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Research Paper</title>
    <style>
        @media print {{
            @page {{ size: A4; margin: 2.5cm; }}
            body {{ margin: 0; }}
        }}
        body {{
            font-family: 'Georgia', 'Times New Roman', serif;
            line-height: 1.8;
            color: #1a1a1a;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background: white;
        }}
        h1 {{
            font-size: 28px;
            color: #000;
            text-align: center;
            margin-bottom: 10px;
            font-weight: bold;
        }}
        h2 {{
            font-size: 20px;
            color: #2c3e50;
            margin-top: 30px;
            margin-bottom: 15px;
            border-bottom: 2px solid #3498db;
            padding-bottom: 5px;
        }}
        h3 {{
            font-size: 16px;
            color: #34495e;
            margin-top: 20px;
            margin-bottom: 10px;
        }}
        p {{
            text-align: justify;
            margin-bottom: 12px;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
            font-size: 14px;
        }}
        th, td {{
            border: 1px solid #333;
            padding: 10px;
            text-align: left;
        }}
        th {{
            background-color: #2c3e50;
            color: white;
            font-weight: bold;
        }}
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        code {{
            background-color: #f4f4f4;
            padding: 2px 5px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 13px;
        }}
        pre {{
            background-color: #2c3e50;
            color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            font-size: 13px;
        }}
        pre code {{
            background-color: transparent;
            color: #ecf0f1;
        }}
        strong {{
            color: #c0392b;
            font-weight: bold;
        }}
        em {{
            font-style: italic;
            color: #7f8c8d;
        }}
        ul, ol {{
            margin-left: 20px;
        }}
        li {{
            margin-bottom: 8px;
        }}
        hr {{
            border: none;
            border-top: 1px solid #bdc3c7;
            margin: 30px 0;
        }}
    </style>
</head>
<body>
{html_body}
<hr>
<p style="text-align: center; color: #7f8c8d; font-size: 12px;">
    Generated by ZETAGRID Research Team | {Path(md_path).stem}
</p>
</body>
</html>"""
    
    # Write HTML
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(styled_html)
    
    print(f"✅ Created: {html_path}")
    return html_path

if __name__ == "__main__":
    brain_dir = Path(r"C:\Users\PC\.gemini\antigravity\brain\0660b146-485e-4e35-a281-e61643ef174a")
    output_dir = Path(r"c:\Users\PC\Desktop\cpu-da")
    
    papers = [
        ("ZETAGRID_PAPER.md", "ZETAGRID_PAPER.html"),
        ("CPU_DA_PAPER.md", "CPU_DA_PAPER.html")
    ]
    
    for md_name, html_name in papers:
        md_path = brain_dir / md_name
        html_path = output_dir / html_name
        
        if md_path.exists():
            md_to_html(md_path, html_path)
        else:
            print(f"❌ Not found: {md_path}")
    
    print("\n🎉 HTML Conversion Complete!")
    print("\n📄 To create PDFs:")
    print("1. Open each .html file in Chrome/Edge")
    print("2. Press Ctrl+P (Print)")
    print("3. Select 'Save as PDF'")
    print("4. Click 'Save'")
