// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pack_int8_p_hls_fptosi_float_i8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        x,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [31:0] x;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] xs_sign_reg_175;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] val_fu_156_p3;
reg   [7:0] val_reg_180;
wire    ap_block_pp0_stage0;
wire   [31:0] data_fu_40_p1;
wire   [22:0] trunc_ln342_fu_62_p1;
wire   [24:0] mantissa_fu_66_p4;
wire   [7:0] xs_exp_fu_52_p4;
wire   [8:0] zext_ln317_fu_80_p1;
wire   [8:0] add_ln317_fu_84_p2;
wire   [7:0] sub_ln18_fu_98_p2;
wire   [0:0] tmp_fu_90_p3;
wire  signed [8:0] sext_ln18_fu_104_p1;
wire   [8:0] select_ln18_fu_108_p3;
wire  signed [31:0] sext_ln18_1_fu_116_p1;
wire   [54:0] zext_ln15_fu_76_p1;
wire   [54:0] zext_ln18_fu_120_p1;
wire   [54:0] lshr_ln18_fu_124_p2;
wire   [54:0] shl_ln18_fu_130_p2;
wire   [7:0] tmp_2_fu_136_p4;
wire   [7:0] tmp_3_fu_146_p4;
wire   [7:0] sub_ln59_fu_164_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_reset_start_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        val_reg_180 <= val_fu_156_p3;
        xs_sign_reg_175 <= data_fu_40_p1[32'd31];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_start_pp0 = 1'b1;
    end else begin
        ap_reset_start_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln317_fu_84_p2 = ($signed(zext_ln317_fu_80_p1) + $signed(9'd385));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ((xs_sign_reg_175[0:0] == 1'b1) ? sub_ln59_fu_164_p2 : val_reg_180);

assign data_fu_40_p1 = x;

assign lshr_ln18_fu_124_p2 = zext_ln15_fu_76_p1 >> zext_ln18_fu_120_p1;

assign mantissa_fu_66_p4 = {{{{1'd1}, {trunc_ln342_fu_62_p1}}}, {1'd0}};

assign select_ln18_fu_108_p3 = ((tmp_fu_90_p3[0:0] == 1'b1) ? sext_ln18_fu_104_p1 : add_ln317_fu_84_p2);

assign sext_ln18_1_fu_116_p1 = $signed(select_ln18_fu_108_p3);

assign sext_ln18_fu_104_p1 = $signed(sub_ln18_fu_98_p2);

assign shl_ln18_fu_130_p2 = zext_ln15_fu_76_p1 << zext_ln18_fu_120_p1;

assign sub_ln18_fu_98_p2 = (8'd127 - xs_exp_fu_52_p4);

assign sub_ln59_fu_164_p2 = (8'd0 - val_reg_180);

assign tmp_2_fu_136_p4 = {{lshr_ln18_fu_124_p2[31:24]}};

assign tmp_3_fu_146_p4 = {{shl_ln18_fu_130_p2[31:24]}};

assign tmp_fu_90_p3 = add_ln317_fu_84_p2[32'd8];

assign trunc_ln342_fu_62_p1 = data_fu_40_p1[22:0];

assign val_fu_156_p3 = ((tmp_fu_90_p3[0:0] == 1'b1) ? tmp_2_fu_136_p4 : tmp_3_fu_146_p4);

assign xs_exp_fu_52_p4 = {{data_fu_40_p1[30:23]}};

assign zext_ln15_fu_76_p1 = mantissa_fu_66_p4;

assign zext_ln18_fu_120_p1 = $unsigned(sext_ln18_1_fu_116_p1);

assign zext_ln317_fu_80_p1 = xs_exp_fu_52_p4;

endmodule //pack_int8_p_hls_fptosi_float_i8
