// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pack_int4_transpose_pack_int4_transpose_Pipeline_read_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        buffer_31_out,
        buffer_31_out_ap_vld,
        buffer_30_out,
        buffer_30_out_ap_vld,
        buffer_29_out,
        buffer_29_out_ap_vld,
        buffer_28_out,
        buffer_28_out_ap_vld,
        buffer_27_out,
        buffer_27_out_ap_vld,
        buffer_26_out,
        buffer_26_out_ap_vld,
        buffer_25_out,
        buffer_25_out_ap_vld,
        buffer_24_out,
        buffer_24_out_ap_vld,
        buffer_23_out,
        buffer_23_out_ap_vld,
        buffer_22_out,
        buffer_22_out_ap_vld,
        buffer_21_out,
        buffer_21_out_ap_vld,
        buffer_20_out,
        buffer_20_out_ap_vld,
        buffer_19_out,
        buffer_19_out_ap_vld,
        buffer_18_out,
        buffer_18_out_ap_vld,
        buffer_17_out,
        buffer_17_out_ap_vld,
        buffer_16_out,
        buffer_16_out_ap_vld,
        buffer_15_out,
        buffer_15_out_ap_vld,
        buffer_14_out,
        buffer_14_out_ap_vld,
        buffer_13_out,
        buffer_13_out_ap_vld,
        buffer_12_out,
        buffer_12_out_ap_vld,
        buffer_11_out,
        buffer_11_out_ap_vld,
        buffer_10_out,
        buffer_10_out_ap_vld,
        buffer_9_out,
        buffer_9_out_ap_vld,
        buffer_8_out,
        buffer_8_out_ap_vld,
        buffer_7_out,
        buffer_7_out_ap_vld,
        buffer_6_out,
        buffer_6_out_ap_vld,
        buffer_5_out,
        buffer_5_out_ap_vld,
        buffer_4_out,
        buffer_4_out_ap_vld,
        buffer_3_out,
        buffer_3_out_ap_vld,
        buffer_2_out,
        buffer_2_out_ap_vld,
        buffer_1_out,
        buffer_1_out_ap_vld,
        buffer_out,
        buffer_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [3:0] buffer_31_out;
output   buffer_31_out_ap_vld;
output  [3:0] buffer_30_out;
output   buffer_30_out_ap_vld;
output  [3:0] buffer_29_out;
output   buffer_29_out_ap_vld;
output  [3:0] buffer_28_out;
output   buffer_28_out_ap_vld;
output  [3:0] buffer_27_out;
output   buffer_27_out_ap_vld;
output  [3:0] buffer_26_out;
output   buffer_26_out_ap_vld;
output  [3:0] buffer_25_out;
output   buffer_25_out_ap_vld;
output  [3:0] buffer_24_out;
output   buffer_24_out_ap_vld;
output  [3:0] buffer_23_out;
output   buffer_23_out_ap_vld;
output  [3:0] buffer_22_out;
output   buffer_22_out_ap_vld;
output  [3:0] buffer_21_out;
output   buffer_21_out_ap_vld;
output  [3:0] buffer_20_out;
output   buffer_20_out_ap_vld;
output  [3:0] buffer_19_out;
output   buffer_19_out_ap_vld;
output  [3:0] buffer_18_out;
output   buffer_18_out_ap_vld;
output  [3:0] buffer_17_out;
output   buffer_17_out_ap_vld;
output  [3:0] buffer_16_out;
output   buffer_16_out_ap_vld;
output  [3:0] buffer_15_out;
output   buffer_15_out_ap_vld;
output  [3:0] buffer_14_out;
output   buffer_14_out_ap_vld;
output  [3:0] buffer_13_out;
output   buffer_13_out_ap_vld;
output  [3:0] buffer_12_out;
output   buffer_12_out_ap_vld;
output  [3:0] buffer_11_out;
output   buffer_11_out_ap_vld;
output  [3:0] buffer_10_out;
output   buffer_10_out_ap_vld;
output  [3:0] buffer_9_out;
output   buffer_9_out_ap_vld;
output  [3:0] buffer_8_out;
output   buffer_8_out_ap_vld;
output  [3:0] buffer_7_out;
output   buffer_7_out_ap_vld;
output  [3:0] buffer_6_out;
output   buffer_6_out_ap_vld;
output  [3:0] buffer_5_out;
output   buffer_5_out_ap_vld;
output  [3:0] buffer_4_out;
output   buffer_4_out_ap_vld;
output  [3:0] buffer_3_out;
output   buffer_3_out_ap_vld;
output  [3:0] buffer_2_out;
output   buffer_2_out_ap_vld;
output  [3:0] buffer_1_out;
output   buffer_1_out_ap_vld;
output  [3:0] buffer_out;
output   buffer_out_ap_vld;

reg ap_idle;
reg in_stream_TREADY;
reg buffer_31_out_ap_vld;
reg buffer_30_out_ap_vld;
reg buffer_29_out_ap_vld;
reg buffer_28_out_ap_vld;
reg buffer_27_out_ap_vld;
reg buffer_26_out_ap_vld;
reg buffer_25_out_ap_vld;
reg buffer_24_out_ap_vld;
reg buffer_23_out_ap_vld;
reg buffer_22_out_ap_vld;
reg buffer_21_out_ap_vld;
reg buffer_20_out_ap_vld;
reg buffer_19_out_ap_vld;
reg buffer_18_out_ap_vld;
reg buffer_17_out_ap_vld;
reg buffer_16_out_ap_vld;
reg buffer_15_out_ap_vld;
reg buffer_14_out_ap_vld;
reg buffer_13_out_ap_vld;
reg buffer_12_out_ap_vld;
reg buffer_11_out_ap_vld;
reg buffer_10_out_ap_vld;
reg buffer_9_out_ap_vld;
reg buffer_8_out_ap_vld;
reg buffer_7_out_ap_vld;
reg buffer_6_out_ap_vld;
reg buffer_5_out_ap_vld;
reg buffer_4_out_ap_vld;
reg buffer_3_out_ap_vld;
reg buffer_2_out_ap_vld;
reg buffer_1_out_ap_vld;
reg buffer_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln32_fu_592_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln32_reg_1274;
wire   [4:0] trunc_ln32_fu_604_p1;
reg   [4:0] trunc_ln32_reg_1278;
reg   [0:0] xs_sign_reg_1282;
wire   [22:0] trunc_ln342_fu_630_p1;
reg   [22:0] trunc_ln342_reg_1287;
wire   [0:0] tmp_fu_644_p3;
reg   [0:0] tmp_reg_1292;
wire   [8:0] select_ln18_fu_662_p3;
reg   [8:0] select_ln18_reg_1297;
wire   [7:0] result_fu_740_p3;
reg   [7:0] result_reg_1302;
reg   [4:0] tmp_1_reg_1307;
reg   [5:0] j_fu_216;
wire   [5:0] add_ln32_fu_598_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_1;
reg   [3:0] buffer_fu_220;
wire   [3:0] buffer_32_fu_779_p3;
reg    ap_predicate_pred268_state3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [3:0] buffer_1_fu_224;
reg    ap_predicate_pred283_state3;
reg   [3:0] buffer_2_fu_228;
reg    ap_predicate_pred292_state3;
reg   [3:0] buffer_3_fu_232;
reg    ap_predicate_pred301_state3;
reg   [3:0] buffer_4_fu_236;
reg    ap_predicate_pred310_state3;
reg   [3:0] buffer_5_fu_240;
reg    ap_predicate_pred319_state3;
reg   [3:0] buffer_6_fu_244;
reg    ap_predicate_pred328_state3;
reg   [3:0] buffer_7_fu_248;
reg    ap_predicate_pred337_state3;
reg   [3:0] buffer_8_fu_252;
reg    ap_predicate_pred346_state3;
reg   [3:0] buffer_9_fu_256;
reg    ap_predicate_pred355_state3;
reg   [3:0] buffer_10_fu_260;
reg    ap_predicate_pred364_state3;
reg   [3:0] buffer_11_fu_264;
reg    ap_predicate_pred373_state3;
reg   [3:0] buffer_12_fu_268;
reg    ap_predicate_pred382_state3;
reg   [3:0] buffer_13_fu_272;
reg    ap_predicate_pred391_state3;
reg   [3:0] buffer_14_fu_276;
reg    ap_predicate_pred400_state3;
reg   [3:0] buffer_15_fu_280;
reg    ap_predicate_pred409_state3;
reg   [3:0] buffer_16_fu_284;
reg    ap_predicate_pred418_state3;
reg   [3:0] buffer_17_fu_288;
reg    ap_predicate_pred427_state3;
reg   [3:0] buffer_18_fu_292;
reg    ap_predicate_pred436_state3;
reg   [3:0] buffer_19_fu_296;
reg    ap_predicate_pred445_state3;
reg   [3:0] buffer_20_fu_300;
reg    ap_predicate_pred454_state3;
reg   [3:0] buffer_21_fu_304;
reg    ap_predicate_pred463_state3;
reg   [3:0] buffer_22_fu_308;
reg    ap_predicate_pred472_state3;
reg   [3:0] buffer_23_fu_312;
reg    ap_predicate_pred481_state3;
reg   [3:0] buffer_24_fu_316;
reg    ap_predicate_pred490_state3;
reg   [3:0] buffer_25_fu_320;
reg    ap_predicate_pred499_state3;
reg   [3:0] buffer_26_fu_324;
reg    ap_predicate_pred508_state3;
reg   [3:0] buffer_27_fu_328;
reg    ap_predicate_pred517_state3;
reg   [3:0] buffer_28_fu_332;
reg    ap_predicate_pred526_state3;
reg   [3:0] buffer_29_fu_336;
reg    ap_predicate_pred535_state3;
reg   [3:0] buffer_30_fu_340;
reg    ap_predicate_pred544_state3;
reg   [3:0] buffer_31_fu_344;
reg    ap_predicate_pred553_state3;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] xs_exp_fu_620_p4;
wire   [8:0] zext_ln317_fu_634_p1;
wire   [8:0] add_ln317_fu_638_p2;
wire   [7:0] sub_ln18_fu_652_p2;
wire  signed [8:0] sext_ln18_fu_658_p1;
wire   [24:0] mantissa_fu_675_p4;
wire  signed [31:0] sext_ln18_1_fu_688_p1;
wire   [54:0] zext_ln15_fu_684_p1;
wire   [54:0] zext_ln18_fu_691_p1;
wire   [54:0] lshr_ln18_fu_695_p2;
wire   [54:0] shl_ln18_fu_701_p2;
wire   [7:0] tmp_3_fu_707_p4;
wire   [7:0] tmp_4_fu_717_p4;
wire   [7:0] val_fu_727_p3;
wire   [7:0] sub_ln59_fu_734_p2;
wire   [0:0] icmp_ln41_fu_757_p2;
wire   [7:0] i8_1_fu_762_p3;
wire   [0:0] icmp_ln42_fu_769_p2;
wire   [3:0] trunc_ln44_fu_775_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_216 = 6'd0;
#0 buffer_fu_220 = 4'd0;
#0 buffer_1_fu_224 = 4'd0;
#0 buffer_2_fu_228 = 4'd0;
#0 buffer_3_fu_232 = 4'd0;
#0 buffer_4_fu_236 = 4'd0;
#0 buffer_5_fu_240 = 4'd0;
#0 buffer_6_fu_244 = 4'd0;
#0 buffer_7_fu_248 = 4'd0;
#0 buffer_8_fu_252 = 4'd0;
#0 buffer_9_fu_256 = 4'd0;
#0 buffer_10_fu_260 = 4'd0;
#0 buffer_11_fu_264 = 4'd0;
#0 buffer_12_fu_268 = 4'd0;
#0 buffer_13_fu_272 = 4'd0;
#0 buffer_14_fu_276 = 4'd0;
#0 buffer_15_fu_280 = 4'd0;
#0 buffer_16_fu_284 = 4'd0;
#0 buffer_17_fu_288 = 4'd0;
#0 buffer_18_fu_292 = 4'd0;
#0 buffer_19_fu_296 = 4'd0;
#0 buffer_20_fu_300 = 4'd0;
#0 buffer_21_fu_304 = 4'd0;
#0 buffer_22_fu_308 = 4'd0;
#0 buffer_23_fu_312 = 4'd0;
#0 buffer_24_fu_316 = 4'd0;
#0 buffer_25_fu_320 = 4'd0;
#0 buffer_26_fu_324 = 4'd0;
#0 buffer_27_fu_328 = 4'd0;
#0 buffer_28_fu_332 = 4'd0;
#0 buffer_29_fu_336 = 4'd0;
#0 buffer_30_fu_340 = 4'd0;
#0 buffer_31_fu_344 = 4'd0;
#0 ap_done_reg = 1'b0;
end

pack_int4_transpose_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_592_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            j_fu_216 <= add_ln32_fu_598_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_216 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_predicate_pred268_state3 <= (trunc_ln32_reg_1278 == 5'd0);
        ap_predicate_pred283_state3 <= (trunc_ln32_reg_1278 == 5'd1);
        ap_predicate_pred292_state3 <= (trunc_ln32_reg_1278 == 5'd2);
        ap_predicate_pred301_state3 <= (trunc_ln32_reg_1278 == 5'd3);
        ap_predicate_pred310_state3 <= (trunc_ln32_reg_1278 == 5'd4);
        ap_predicate_pred319_state3 <= (trunc_ln32_reg_1278 == 5'd5);
        ap_predicate_pred328_state3 <= (trunc_ln32_reg_1278 == 5'd6);
        ap_predicate_pred337_state3 <= (trunc_ln32_reg_1278 == 5'd7);
        ap_predicate_pred346_state3 <= (trunc_ln32_reg_1278 == 5'd8);
        ap_predicate_pred355_state3 <= (trunc_ln32_reg_1278 == 5'd9);
        ap_predicate_pred364_state3 <= (trunc_ln32_reg_1278 == 5'd10);
        ap_predicate_pred373_state3 <= (trunc_ln32_reg_1278 == 5'd11);
        ap_predicate_pred382_state3 <= (trunc_ln32_reg_1278 == 5'd12);
        ap_predicate_pred391_state3 <= (trunc_ln32_reg_1278 == 5'd13);
        ap_predicate_pred400_state3 <= (trunc_ln32_reg_1278 == 5'd14);
        ap_predicate_pred409_state3 <= (trunc_ln32_reg_1278 == 5'd15);
        ap_predicate_pred418_state3 <= (trunc_ln32_reg_1278 == 5'd16);
        ap_predicate_pred427_state3 <= (trunc_ln32_reg_1278 == 5'd17);
        ap_predicate_pred436_state3 <= (trunc_ln32_reg_1278 == 5'd18);
        ap_predicate_pred445_state3 <= (trunc_ln32_reg_1278 == 5'd19);
        ap_predicate_pred454_state3 <= (trunc_ln32_reg_1278 == 5'd20);
        ap_predicate_pred463_state3 <= (trunc_ln32_reg_1278 == 5'd21);
        ap_predicate_pred472_state3 <= (trunc_ln32_reg_1278 == 5'd22);
        ap_predicate_pred481_state3 <= (trunc_ln32_reg_1278 == 5'd23);
        ap_predicate_pred490_state3 <= (trunc_ln32_reg_1278 == 5'd24);
        ap_predicate_pred499_state3 <= (trunc_ln32_reg_1278 == 5'd25);
        ap_predicate_pred508_state3 <= (trunc_ln32_reg_1278 == 5'd26);
        ap_predicate_pred517_state3 <= (trunc_ln32_reg_1278 == 5'd27);
        ap_predicate_pred526_state3 <= (trunc_ln32_reg_1278 == 5'd28);
        ap_predicate_pred535_state3 <= (trunc_ln32_reg_1278 == 5'd29);
        ap_predicate_pred544_state3 <= (trunc_ln32_reg_1278 == 5'd30);
        ap_predicate_pred553_state3 <= (trunc_ln32_reg_1278 == 5'd31);
        icmp_ln32_reg_1274 <= icmp_ln32_fu_592_p2;
        result_reg_1302 <= result_fu_740_p3;
        select_ln18_reg_1297 <= select_ln18_fu_662_p3;
        tmp_1_reg_1307 <= {{result_fu_740_p3[7:3]}};
        tmp_reg_1292 <= add_ln317_fu_638_p2[32'd8];
        trunc_ln32_reg_1278 <= trunc_ln32_fu_604_p1;
        trunc_ln342_reg_1287 <= trunc_ln342_fu_630_p1;
        xs_sign_reg_1282 <= in_stream_TDATA[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred364_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_10_fu_260 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred373_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_11_fu_264 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred382_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_12_fu_268 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred391_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_13_fu_272 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred400_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_14_fu_276 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred409_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_15_fu_280 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred418_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_16_fu_284 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred427_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_17_fu_288 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred436_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_18_fu_292 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred445_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_19_fu_296 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred283_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_1_fu_224 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred454_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_20_fu_300 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred463_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_21_fu_304 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred472_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_22_fu_308 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred481_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_23_fu_312 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred490_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_24_fu_316 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred499_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_25_fu_320 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred508_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_26_fu_324 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred517_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_27_fu_328 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred526_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_28_fu_332 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred535_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_29_fu_336 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred292_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_2_fu_228 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred544_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_30_fu_340 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred553_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_31_fu_344 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred301_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_3_fu_232 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred310_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_4_fu_236 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred319_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_5_fu_240 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred328_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_6_fu_244 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred337_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_7_fu_248 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred346_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_8_fu_252 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred355_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_9_fu_256 <= buffer_32_fu_779_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred268_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_fu_220 <= buffer_32_fu_779_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln32_fu_592_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_216;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_10_out_ap_vld = 1'b1;
    end else begin
        buffer_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_11_out_ap_vld = 1'b1;
    end else begin
        buffer_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_12_out_ap_vld = 1'b1;
    end else begin
        buffer_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_13_out_ap_vld = 1'b1;
    end else begin
        buffer_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_14_out_ap_vld = 1'b1;
    end else begin
        buffer_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_15_out_ap_vld = 1'b1;
    end else begin
        buffer_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_16_out_ap_vld = 1'b1;
    end else begin
        buffer_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_17_out_ap_vld = 1'b1;
    end else begin
        buffer_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_18_out_ap_vld = 1'b1;
    end else begin
        buffer_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_19_out_ap_vld = 1'b1;
    end else begin
        buffer_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_out_ap_vld = 1'b1;
    end else begin
        buffer_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_20_out_ap_vld = 1'b1;
    end else begin
        buffer_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_21_out_ap_vld = 1'b1;
    end else begin
        buffer_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_22_out_ap_vld = 1'b1;
    end else begin
        buffer_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_23_out_ap_vld = 1'b1;
    end else begin
        buffer_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_24_out_ap_vld = 1'b1;
    end else begin
        buffer_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_25_out_ap_vld = 1'b1;
    end else begin
        buffer_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_26_out_ap_vld = 1'b1;
    end else begin
        buffer_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_27_out_ap_vld = 1'b1;
    end else begin
        buffer_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_28_out_ap_vld = 1'b1;
    end else begin
        buffer_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_29_out_ap_vld = 1'b1;
    end else begin
        buffer_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_2_out_ap_vld = 1'b1;
    end else begin
        buffer_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_30_out_ap_vld = 1'b1;
    end else begin
        buffer_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_31_out_ap_vld = 1'b1;
    end else begin
        buffer_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_3_out_ap_vld = 1'b1;
    end else begin
        buffer_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_4_out_ap_vld = 1'b1;
    end else begin
        buffer_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_5_out_ap_vld = 1'b1;
    end else begin
        buffer_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_6_out_ap_vld = 1'b1;
    end else begin
        buffer_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_7_out_ap_vld = 1'b1;
    end else begin
        buffer_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_8_out_ap_vld = 1'b1;
    end else begin
        buffer_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_9_out_ap_vld = 1'b1;
    end else begin
        buffer_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_1274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_out_ap_vld = 1'b1;
    end else begin
        buffer_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln32_fu_592_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_fu_592_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln317_fu_638_p2 = ($signed(zext_ln317_fu_634_p1) + $signed(9'd385));

assign add_ln32_fu_598_p2 = (ap_sig_allocacmp_j_1 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln32_fu_592_p2 == 1'd0) & (in_stream_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_10_out = buffer_10_fu_260;

assign buffer_11_out = buffer_11_fu_264;

assign buffer_12_out = buffer_12_fu_268;

assign buffer_13_out = buffer_13_fu_272;

assign buffer_14_out = buffer_14_fu_276;

assign buffer_15_out = buffer_15_fu_280;

assign buffer_16_out = buffer_16_fu_284;

assign buffer_17_out = buffer_17_fu_288;

assign buffer_18_out = buffer_18_fu_292;

assign buffer_19_out = buffer_19_fu_296;

assign buffer_1_out = buffer_1_fu_224;

assign buffer_20_out = buffer_20_fu_300;

assign buffer_21_out = buffer_21_fu_304;

assign buffer_22_out = buffer_22_fu_308;

assign buffer_23_out = buffer_23_fu_312;

assign buffer_24_out = buffer_24_fu_316;

assign buffer_25_out = buffer_25_fu_320;

assign buffer_26_out = buffer_26_fu_324;

assign buffer_27_out = buffer_27_fu_328;

assign buffer_28_out = buffer_28_fu_332;

assign buffer_29_out = buffer_29_fu_336;

assign buffer_2_out = buffer_2_fu_228;

assign buffer_30_out = buffer_30_fu_340;

assign buffer_31_out = buffer_31_fu_344;

assign buffer_32_fu_779_p3 = ((icmp_ln42_fu_769_p2[0:0] == 1'b1) ? 4'd8 : trunc_ln44_fu_775_p1);

assign buffer_3_out = buffer_3_fu_232;

assign buffer_4_out = buffer_4_fu_236;

assign buffer_5_out = buffer_5_fu_240;

assign buffer_6_out = buffer_6_fu_244;

assign buffer_7_out = buffer_7_fu_248;

assign buffer_8_out = buffer_8_fu_252;

assign buffer_9_out = buffer_9_fu_256;

assign buffer_out = buffer_fu_220;

assign i8_1_fu_762_p3 = ((icmp_ln41_fu_757_p2[0:0] == 1'b1) ? 8'd7 : result_reg_1302);

assign icmp_ln32_fu_592_p2 = ((ap_sig_allocacmp_j_1 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_757_p2 = (($signed(tmp_1_reg_1307) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_769_p2 = (($signed(i8_1_fu_762_p3) < $signed(8'd248)) ? 1'b1 : 1'b0);

assign lshr_ln18_fu_695_p2 = zext_ln15_fu_684_p1 >> zext_ln18_fu_691_p1;

assign mantissa_fu_675_p4 = {{{{1'd1}, {trunc_ln342_reg_1287}}}, {1'd0}};

assign result_fu_740_p3 = ((xs_sign_reg_1282[0:0] == 1'b1) ? sub_ln59_fu_734_p2 : val_fu_727_p3);

assign select_ln18_fu_662_p3 = ((tmp_fu_644_p3[0:0] == 1'b1) ? sext_ln18_fu_658_p1 : add_ln317_fu_638_p2);

assign sext_ln18_1_fu_688_p1 = $signed(select_ln18_reg_1297);

assign sext_ln18_fu_658_p1 = $signed(sub_ln18_fu_652_p2);

assign shl_ln18_fu_701_p2 = zext_ln15_fu_684_p1 << zext_ln18_fu_691_p1;

assign sub_ln18_fu_652_p2 = (8'd127 - xs_exp_fu_620_p4);

assign sub_ln59_fu_734_p2 = (8'd0 - val_fu_727_p3);

assign tmp_3_fu_707_p4 = {{lshr_ln18_fu_695_p2[31:24]}};

assign tmp_4_fu_717_p4 = {{shl_ln18_fu_701_p2[31:24]}};

assign tmp_fu_644_p3 = add_ln317_fu_638_p2[32'd8];

assign trunc_ln32_fu_604_p1 = ap_sig_allocacmp_j_1[4:0];

assign trunc_ln342_fu_630_p1 = in_stream_TDATA[22:0];

assign trunc_ln44_fu_775_p1 = i8_1_fu_762_p3[3:0];

assign val_fu_727_p3 = ((tmp_reg_1292[0:0] == 1'b1) ? tmp_3_fu_707_p4 : tmp_4_fu_717_p4);

assign xs_exp_fu_620_p4 = {{in_stream_TDATA[30:23]}};

assign zext_ln15_fu_684_p1 = mantissa_fu_675_p4;

assign zext_ln18_fu_691_p1 = $unsigned(sext_ln18_1_fu_688_p1);

assign zext_ln317_fu_634_p1 = xs_exp_fu_620_p4;

endmodule //pack_int4_transpose_pack_int4_transpose_Pipeline_read_loop
