// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pack_int4_transpose_pack_int4_transpose,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.364000,HLS_SYN_LAT=1308622811,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=444,HLS_SYN_LUT=924,HLS_VERSION=2024_1}" *)

module pack_int4_transpose (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [127:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [15:0] out_stream_TKEEP;
output  [15:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] num_elements;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [0:0] tmp_reg_754;
reg   [26:0] tmp_1_reg_759;
reg   [26:0] tmp_2_reg_764;
wire   [27:0] num_blocks_fu_349_p3;
reg   [27:0] num_blocks_reg_769;
wire    ap_CS_fsm_state2;
wire   [27:0] sub_fu_356_p2;
reg   [27:0] sub_reg_774;
wire   [0:0] p_out_last_fu_380_p2;
reg   [0:0] p_out_last_reg_782;
wire    ap_CS_fsm_state3;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_idle;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_ready;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_in_stream_TREADY;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out_ap_vld;
wire   [3:0] grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out;
wire    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out_ap_vld;
reg    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
wire   [0:0] icmp_ln23_fu_369_p2;
wire    ap_CS_fsm_state4;
reg   [26:0] i_fu_98;
wire   [26:0] i_2_fu_374_p2;
wire   [31:0] sub_ln21_fu_306_p2;
wire   [27:0] zext_ln21_fu_337_p1;
wire   [27:0] sub_ln21_1_fu_340_p2;
wire   [27:0] zext_ln21_1_fu_346_p1;
wire   [27:0] zext_ln23_fu_365_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire   [127:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire   [15:0] out_stream_TSTRB_int_regslice;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg = 1'b0;
#0 i_fu_98 = 27'd0;
end

pack_int4_transpose_pack_int4_transpose_Pipeline_read_loop grp_pack_int4_transpose_Pipeline_read_loop_fu_254(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start),
    .ap_done(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done),
    .ap_idle(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_idle),
    .ap_ready(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .buffer_31_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out),
    .buffer_31_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out_ap_vld),
    .buffer_30_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out),
    .buffer_30_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out_ap_vld),
    .buffer_29_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out),
    .buffer_29_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out_ap_vld),
    .buffer_28_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out),
    .buffer_28_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out_ap_vld),
    .buffer_27_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out),
    .buffer_27_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out_ap_vld),
    .buffer_26_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out),
    .buffer_26_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out_ap_vld),
    .buffer_25_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out),
    .buffer_25_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out_ap_vld),
    .buffer_24_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out),
    .buffer_24_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out_ap_vld),
    .buffer_23_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out),
    .buffer_23_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out_ap_vld),
    .buffer_22_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out),
    .buffer_22_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out_ap_vld),
    .buffer_21_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out),
    .buffer_21_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out_ap_vld),
    .buffer_20_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out),
    .buffer_20_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out_ap_vld),
    .buffer_19_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out),
    .buffer_19_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out_ap_vld),
    .buffer_18_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out),
    .buffer_18_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out_ap_vld),
    .buffer_17_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out),
    .buffer_17_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out_ap_vld),
    .buffer_16_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out),
    .buffer_16_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out_ap_vld),
    .buffer_15_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out),
    .buffer_15_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out_ap_vld),
    .buffer_14_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out),
    .buffer_14_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out_ap_vld),
    .buffer_13_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out),
    .buffer_13_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out_ap_vld),
    .buffer_12_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out),
    .buffer_12_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out_ap_vld),
    .buffer_11_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out),
    .buffer_11_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out_ap_vld),
    .buffer_10_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out),
    .buffer_10_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out_ap_vld),
    .buffer_9_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out),
    .buffer_9_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out_ap_vld),
    .buffer_8_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out),
    .buffer_8_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out_ap_vld),
    .buffer_7_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out),
    .buffer_7_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out_ap_vld),
    .buffer_6_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out),
    .buffer_6_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out_ap_vld),
    .buffer_5_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out),
    .buffer_5_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out_ap_vld),
    .buffer_4_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out),
    .buffer_4_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out_ap_vld),
    .buffer_3_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out),
    .buffer_3_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out_ap_vld),
    .buffer_2_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out),
    .buffer_2_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out_ap_vld),
    .buffer_1_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out),
    .buffer_1_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out_ap_vld),
    .buffer_out(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out),
    .buffer_out_ap_vld(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out_ap_vld)
);

pack_int4_transpose_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_elements(num_elements),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 128 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 16 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(16'd65535),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 16 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TSTRB_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

pack_int4_transpose_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(p_out_last_reg_782),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_369_p2 == 1'd1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
            grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg <= 1'b1;
        end else if ((grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_ready == 1'b1)) begin
            grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_98 <= 27'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_369_p2 == 1'd1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        i_fu_98 <= i_2_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        num_blocks_reg_769 <= num_blocks_fu_349_p3;
        sub_reg_774 <= sub_fu_356_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_out_last_reg_782 <= p_out_last_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_1_reg_759 <= {{sub_ln21_fu_306_p2[31:5]}};
        tmp_2_reg_764 <= {{num_elements[31:5]}};
        tmp_reg_754 <= num_elements[32'd31];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_369_p2 == 1'd0) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_369_p2 == 1'd0) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_stream_TREADY_int_regslice = grp_pack_int4_transpose_Pipeline_read_loop_fu_254_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_369_p2 == 1'd0) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln23_fu_369_p2 == 1'd1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start = grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg;

assign i_2_fu_374_p2 = (i_fu_98 + 27'd1);

assign icmp_ln23_fu_369_p2 = (($signed(zext_ln23_fu_365_p1) < $signed(num_blocks_reg_769)) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign num_blocks_fu_349_p3 = ((tmp_reg_754[0:0] == 1'b1) ? sub_ln21_1_fu_340_p2 : zext_ln21_1_fu_346_p1);

assign out_stream_TDATA_int_regslice = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out}}, 
    {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out}}, {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out}}, 
    {grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out}};

assign out_stream_TSTRB_int_regslice = 'bx;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign p_out_last_fu_380_p2 = ((zext_ln23_fu_365_p1 == sub_reg_774) ? 1'b1 : 1'b0);

assign sub_fu_356_p2 = ($signed(num_blocks_fu_349_p3) + $signed(28'd268435455));

assign sub_ln21_1_fu_340_p2 = (28'd0 - zext_ln21_fu_337_p1);

assign sub_ln21_fu_306_p2 = (32'd0 - num_elements);

assign zext_ln21_1_fu_346_p1 = tmp_2_reg_764;

assign zext_ln21_fu_337_p1 = tmp_1_reg_759;

assign zext_ln23_fu_365_p1 = i_fu_98;

endmodule //pack_int4_transpose
