-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pack_int4_transpose_pack_int4_transpose_Pipeline_read_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    buffer_31_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_31_out_ap_vld : OUT STD_LOGIC;
    buffer_30_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_30_out_ap_vld : OUT STD_LOGIC;
    buffer_29_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_29_out_ap_vld : OUT STD_LOGIC;
    buffer_28_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_28_out_ap_vld : OUT STD_LOGIC;
    buffer_27_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_27_out_ap_vld : OUT STD_LOGIC;
    buffer_26_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_26_out_ap_vld : OUT STD_LOGIC;
    buffer_25_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_25_out_ap_vld : OUT STD_LOGIC;
    buffer_24_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_24_out_ap_vld : OUT STD_LOGIC;
    buffer_23_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_23_out_ap_vld : OUT STD_LOGIC;
    buffer_22_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_22_out_ap_vld : OUT STD_LOGIC;
    buffer_21_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_21_out_ap_vld : OUT STD_LOGIC;
    buffer_20_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_20_out_ap_vld : OUT STD_LOGIC;
    buffer_19_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_19_out_ap_vld : OUT STD_LOGIC;
    buffer_18_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_18_out_ap_vld : OUT STD_LOGIC;
    buffer_17_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_17_out_ap_vld : OUT STD_LOGIC;
    buffer_16_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_16_out_ap_vld : OUT STD_LOGIC;
    buffer_15_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_15_out_ap_vld : OUT STD_LOGIC;
    buffer_14_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_14_out_ap_vld : OUT STD_LOGIC;
    buffer_13_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_13_out_ap_vld : OUT STD_LOGIC;
    buffer_12_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_12_out_ap_vld : OUT STD_LOGIC;
    buffer_11_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_11_out_ap_vld : OUT STD_LOGIC;
    buffer_10_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_10_out_ap_vld : OUT STD_LOGIC;
    buffer_9_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_9_out_ap_vld : OUT STD_LOGIC;
    buffer_8_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_8_out_ap_vld : OUT STD_LOGIC;
    buffer_7_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_7_out_ap_vld : OUT STD_LOGIC;
    buffer_6_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_6_out_ap_vld : OUT STD_LOGIC;
    buffer_5_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_5_out_ap_vld : OUT STD_LOGIC;
    buffer_4_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_4_out_ap_vld : OUT STD_LOGIC;
    buffer_3_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_3_out_ap_vld : OUT STD_LOGIC;
    buffer_2_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_2_out_ap_vld : OUT STD_LOGIC;
    buffer_1_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_1_out_ap_vld : OUT STD_LOGIC;
    buffer_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of pack_int4_transpose_pack_int4_transpose_Pipeline_read_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv8_F8 : STD_LOGIC_VECTOR (7 downto 0) := "11111000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln32_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln32_reg_1274 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln32_fu_604_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln32_reg_1278 : STD_LOGIC_VECTOR (4 downto 0);
    signal xs_sign_reg_1282 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln342_fu_630_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln342_reg_1287 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_fu_644_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1292 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln18_fu_662_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_reg_1297 : STD_LOGIC_VECTOR (8 downto 0);
    signal result_fu_740_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_reg_1302 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_1307 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_fu_216 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln32_fu_598_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal buffer_fu_220 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal buffer_32_fu_779_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_predicate_pred268_state3 : BOOLEAN;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal buffer_1_fu_224 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred283_state3 : BOOLEAN;
    signal buffer_2_fu_228 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred292_state3 : BOOLEAN;
    signal buffer_3_fu_232 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred301_state3 : BOOLEAN;
    signal buffer_4_fu_236 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred310_state3 : BOOLEAN;
    signal buffer_5_fu_240 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred319_state3 : BOOLEAN;
    signal buffer_6_fu_244 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred328_state3 : BOOLEAN;
    signal buffer_7_fu_248 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred337_state3 : BOOLEAN;
    signal buffer_8_fu_252 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred346_state3 : BOOLEAN;
    signal buffer_9_fu_256 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred355_state3 : BOOLEAN;
    signal buffer_10_fu_260 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred364_state3 : BOOLEAN;
    signal buffer_11_fu_264 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred373_state3 : BOOLEAN;
    signal buffer_12_fu_268 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred382_state3 : BOOLEAN;
    signal buffer_13_fu_272 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred391_state3 : BOOLEAN;
    signal buffer_14_fu_276 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred400_state3 : BOOLEAN;
    signal buffer_15_fu_280 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred409_state3 : BOOLEAN;
    signal buffer_16_fu_284 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred418_state3 : BOOLEAN;
    signal buffer_17_fu_288 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred427_state3 : BOOLEAN;
    signal buffer_18_fu_292 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred436_state3 : BOOLEAN;
    signal buffer_19_fu_296 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred445_state3 : BOOLEAN;
    signal buffer_20_fu_300 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred454_state3 : BOOLEAN;
    signal buffer_21_fu_304 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred463_state3 : BOOLEAN;
    signal buffer_22_fu_308 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred472_state3 : BOOLEAN;
    signal buffer_23_fu_312 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred481_state3 : BOOLEAN;
    signal buffer_24_fu_316 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred490_state3 : BOOLEAN;
    signal buffer_25_fu_320 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred499_state3 : BOOLEAN;
    signal buffer_26_fu_324 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred508_state3 : BOOLEAN;
    signal buffer_27_fu_328 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred517_state3 : BOOLEAN;
    signal buffer_28_fu_332 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred526_state3 : BOOLEAN;
    signal buffer_29_fu_336 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred535_state3 : BOOLEAN;
    signal buffer_30_fu_340 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred544_state3 : BOOLEAN;
    signal buffer_31_fu_344 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_predicate_pred553_state3 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal xs_exp_fu_620_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_634_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_638_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_652_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln18_fu_658_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mantissa_fu_675_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln18_1_fu_688_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_684_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal zext_ln18_fu_691_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal lshr_ln18_fu_695_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal shl_ln18_fu_701_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal tmp_3_fu_707_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_717_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val_fu_727_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln59_fu_734_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln41_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i8_1_fu_762_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln42_fu_769_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_fu_775_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pack_int4_transpose_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pack_int4_transpose_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln32_fu_592_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    j_fu_216 <= add_ln32_fu_598_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_216 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                    ap_predicate_pred268_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_0);
                    ap_predicate_pred283_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_1);
                    ap_predicate_pred292_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_2);
                    ap_predicate_pred301_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_3);
                    ap_predicate_pred310_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_4);
                    ap_predicate_pred319_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_5);
                    ap_predicate_pred328_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_6);
                    ap_predicate_pred337_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_7);
                    ap_predicate_pred346_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_8);
                    ap_predicate_pred355_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_9);
                    ap_predicate_pred364_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_A);
                    ap_predicate_pred373_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_B);
                    ap_predicate_pred382_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_C);
                    ap_predicate_pred391_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_D);
                    ap_predicate_pred400_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_E);
                    ap_predicate_pred409_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_F);
                    ap_predicate_pred418_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_10);
                    ap_predicate_pred427_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_11);
                    ap_predicate_pred436_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_12);
                    ap_predicate_pred445_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_13);
                    ap_predicate_pred454_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_14);
                    ap_predicate_pred463_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_15);
                    ap_predicate_pred472_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_16);
                    ap_predicate_pred481_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_17);
                    ap_predicate_pred490_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_18);
                    ap_predicate_pred499_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_19);
                    ap_predicate_pred508_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_1A);
                    ap_predicate_pred517_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_1B);
                    ap_predicate_pred526_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_1C);
                    ap_predicate_pred535_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_1D);
                    ap_predicate_pred544_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_1E);
                    ap_predicate_pred553_state3 <= (trunc_ln32_reg_1278 = ap_const_lv5_1F);
                icmp_ln32_reg_1274 <= icmp_ln32_fu_592_p2;
                result_reg_1302 <= result_fu_740_p3;
                select_ln18_reg_1297 <= select_ln18_fu_662_p3;
                tmp_1_reg_1307 <= result_fu_740_p3(7 downto 3);
                tmp_reg_1292 <= add_ln317_fu_638_p2(8 downto 8);
                trunc_ln32_reg_1278 <= trunc_ln32_fu_604_p1;
                trunc_ln342_reg_1287 <= trunc_ln342_fu_630_p1;
                xs_sign_reg_1282 <= in_stream_TDATA(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred364_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_10_fu_260 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred373_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_11_fu_264 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred382_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_12_fu_268 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred391_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_13_fu_272 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred400_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_14_fu_276 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred409_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_15_fu_280 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred418_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_16_fu_284 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred427_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_17_fu_288 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred436_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_18_fu_292 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred445_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_19_fu_296 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred283_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_1_fu_224 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred454_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_20_fu_300 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred463_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_21_fu_304 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred472_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_22_fu_308 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred481_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_23_fu_312 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred490_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_24_fu_316 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred499_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_25_fu_320 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred508_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_26_fu_324 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred517_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_27_fu_328 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred526_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_28_fu_332 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred535_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_29_fu_336 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred292_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_2_fu_228 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred544_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_30_fu_340 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred553_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_31_fu_344 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred301_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_3_fu_232 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred310_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_4_fu_236 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred319_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_5_fu_240 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred328_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_6_fu_244 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred337_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_7_fu_248 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred346_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_8_fu_252 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred355_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_9_fu_256 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred268_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                buffer_fu_220 <= buffer_32_fu_779_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln317_fu_638_p2 <= std_logic_vector(unsigned(zext_ln317_fu_634_p1) + unsigned(ap_const_lv9_181));
    add_ln32_fu_598_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID, icmp_ln32_fu_592_p2)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln32_fu_592_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln32_fu_592_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln32_fu_592_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_216, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_216;
        end if; 
    end process;

    buffer_10_out <= buffer_10_fu_260;

    buffer_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_10_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_11_out <= buffer_11_fu_264;

    buffer_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_11_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_12_out <= buffer_12_fu_268;

    buffer_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_12_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_13_out <= buffer_13_fu_272;

    buffer_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_13_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_14_out <= buffer_14_fu_276;

    buffer_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_14_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_15_out <= buffer_15_fu_280;

    buffer_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_15_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_16_out <= buffer_16_fu_284;

    buffer_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_16_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_17_out <= buffer_17_fu_288;

    buffer_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_17_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_18_out <= buffer_18_fu_292;

    buffer_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_18_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_19_out <= buffer_19_fu_296;

    buffer_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_19_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_1_out <= buffer_1_fu_224;

    buffer_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_1_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_20_out <= buffer_20_fu_300;

    buffer_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_20_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_21_out <= buffer_21_fu_304;

    buffer_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_21_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_22_out <= buffer_22_fu_308;

    buffer_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_22_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_23_out <= buffer_23_fu_312;

    buffer_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_23_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_24_out <= buffer_24_fu_316;

    buffer_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_24_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_25_out <= buffer_25_fu_320;

    buffer_25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_25_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_26_out <= buffer_26_fu_324;

    buffer_26_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_26_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_27_out <= buffer_27_fu_328;

    buffer_27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_27_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_28_out <= buffer_28_fu_332;

    buffer_28_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_28_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_29_out <= buffer_29_fu_336;

    buffer_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_29_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_2_out <= buffer_2_fu_228;

    buffer_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_2_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_30_out <= buffer_30_fu_340;

    buffer_30_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_30_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_31_out <= buffer_31_fu_344;

    buffer_31_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_31_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_32_fu_779_p3 <= 
        ap_const_lv4_8 when (icmp_ln42_fu_769_p2(0) = '1') else 
        trunc_ln44_fu_775_p1;
    buffer_3_out <= buffer_3_fu_232;

    buffer_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_3_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_4_out <= buffer_4_fu_236;

    buffer_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_4_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_5_out <= buffer_5_fu_240;

    buffer_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_5_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_6_out <= buffer_6_fu_244;

    buffer_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_6_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_7_out <= buffer_7_fu_248;

    buffer_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_7_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_8_out <= buffer_8_fu_252;

    buffer_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_8_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_9_out <= buffer_9_fu_256;

    buffer_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_9_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    buffer_out <= buffer_fu_220;

    buffer_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln32_reg_1274, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln32_reg_1274 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_out_ap_vld <= ap_const_logic_1;
        else 
            buffer_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    i8_1_fu_762_p3 <= 
        ap_const_lv8_7 when (icmp_ln41_fu_757_p2(0) = '1') else 
        result_reg_1302;
    icmp_ln32_fu_592_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv6_20) else "0";
    icmp_ln41_fu_757_p2 <= "1" when (signed(tmp_1_reg_1307) > signed(ap_const_lv5_0)) else "0";
    icmp_ln42_fu_769_p2 <= "1" when (signed(i8_1_fu_762_p3) < signed(ap_const_lv8_F8)) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, in_stream_TVALID, icmp_ln32_fu_592_p2, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln32_fu_592_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln32_fu_592_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln32_fu_592_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln18_fu_695_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_684_p1),to_integer(unsigned('0' & zext_ln18_fu_691_p1(31-1 downto 0)))));
    mantissa_fu_675_p4 <= ((ap_const_lv1_1 & trunc_ln342_reg_1287) & ap_const_lv1_0);
    result_fu_740_p3 <= 
        sub_ln59_fu_734_p2 when (xs_sign_reg_1282(0) = '1') else 
        val_fu_727_p3;
    select_ln18_fu_662_p3 <= 
        sext_ln18_fu_658_p1 when (tmp_fu_644_p3(0) = '1') else 
        add_ln317_fu_638_p2;
        sext_ln18_1_fu_688_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_reg_1297),32));

        sext_ln18_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_652_p2),9));

    shl_ln18_fu_701_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_684_p1),to_integer(unsigned('0' & zext_ln18_fu_691_p1(31-1 downto 0)))));
    sub_ln18_fu_652_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_620_p4));
    sub_ln59_fu_734_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(val_fu_727_p3));
    tmp_3_fu_707_p4 <= lshr_ln18_fu_695_p2(31 downto 24);
    tmp_4_fu_717_p4 <= shl_ln18_fu_701_p2(31 downto 24);
    tmp_fu_644_p3 <= add_ln317_fu_638_p2(8 downto 8);
    trunc_ln32_fu_604_p1 <= ap_sig_allocacmp_j_1(5 - 1 downto 0);
    trunc_ln342_fu_630_p1 <= in_stream_TDATA(23 - 1 downto 0);
    trunc_ln44_fu_775_p1 <= i8_1_fu_762_p3(4 - 1 downto 0);
    val_fu_727_p3 <= 
        tmp_3_fu_707_p4 when (tmp_reg_1292(0) = '1') else 
        tmp_4_fu_717_p4;
    xs_exp_fu_620_p4 <= in_stream_TDATA(30 downto 23);
    zext_ln15_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_675_p4),55));
    zext_ln18_fu_691_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_1_fu_688_p1),55));
    zext_ln317_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_620_p4),9));
end behav;
