-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pack_int4_transpose is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of pack_int4_transpose is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pack_int4_transpose_pack_int4_transpose,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.364000,HLS_SYN_LAT=1308622811,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=444,HLS_SYN_LUT=924,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv28_FFFFFFF : STD_LOGIC_VECTOR (27 downto 0) := "1111111111111111111111111111";
    constant ap_const_lv27_1 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal num_elements : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_reg_754 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_759 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_2_reg_764 : STD_LOGIC_VECTOR (26 downto 0);
    signal num_blocks_fu_349_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal num_blocks_reg_769 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub_fu_356_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_reg_774 : STD_LOGIC_VECTOR (27 downto 0);
    signal p_out_last_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_out_last_reg_782 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_idle : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_ready : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_in_stream_TREADY : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out_ap_vld : STD_LOGIC;
    signal grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg : STD_LOGIC := '0';
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal icmp_ln23_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_fu_98 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    signal i_2_fu_374_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal sub_ln21_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln21_fu_337_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln21_1_fu_340_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln21_1_fu_346_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln23_fu_365_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pack_int4_transpose_pack_int4_transpose_Pipeline_read_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        buffer_31_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_31_out_ap_vld : OUT STD_LOGIC;
        buffer_30_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_30_out_ap_vld : OUT STD_LOGIC;
        buffer_29_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_29_out_ap_vld : OUT STD_LOGIC;
        buffer_28_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_28_out_ap_vld : OUT STD_LOGIC;
        buffer_27_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_27_out_ap_vld : OUT STD_LOGIC;
        buffer_26_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_26_out_ap_vld : OUT STD_LOGIC;
        buffer_25_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_25_out_ap_vld : OUT STD_LOGIC;
        buffer_24_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_24_out_ap_vld : OUT STD_LOGIC;
        buffer_23_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_23_out_ap_vld : OUT STD_LOGIC;
        buffer_22_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_22_out_ap_vld : OUT STD_LOGIC;
        buffer_21_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_21_out_ap_vld : OUT STD_LOGIC;
        buffer_20_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_20_out_ap_vld : OUT STD_LOGIC;
        buffer_19_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_19_out_ap_vld : OUT STD_LOGIC;
        buffer_18_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_18_out_ap_vld : OUT STD_LOGIC;
        buffer_17_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_17_out_ap_vld : OUT STD_LOGIC;
        buffer_16_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_16_out_ap_vld : OUT STD_LOGIC;
        buffer_15_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_15_out_ap_vld : OUT STD_LOGIC;
        buffer_14_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_14_out_ap_vld : OUT STD_LOGIC;
        buffer_13_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_13_out_ap_vld : OUT STD_LOGIC;
        buffer_12_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_12_out_ap_vld : OUT STD_LOGIC;
        buffer_11_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_11_out_ap_vld : OUT STD_LOGIC;
        buffer_10_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_10_out_ap_vld : OUT STD_LOGIC;
        buffer_9_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_9_out_ap_vld : OUT STD_LOGIC;
        buffer_8_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_8_out_ap_vld : OUT STD_LOGIC;
        buffer_7_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_7_out_ap_vld : OUT STD_LOGIC;
        buffer_6_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_6_out_ap_vld : OUT STD_LOGIC;
        buffer_5_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_5_out_ap_vld : OUT STD_LOGIC;
        buffer_4_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_4_out_ap_vld : OUT STD_LOGIC;
        buffer_3_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_3_out_ap_vld : OUT STD_LOGIC;
        buffer_2_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_2_out_ap_vld : OUT STD_LOGIC;
        buffer_1_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_1_out_ap_vld : OUT STD_LOGIC;
        buffer_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_out_ap_vld : OUT STD_LOGIC );
    end component;


    component pack_int4_transpose_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        num_elements : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component pack_int4_transpose_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_pack_int4_transpose_Pipeline_read_loop_fu_254 : component pack_int4_transpose_pack_int4_transpose_Pipeline_read_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start,
        ap_done => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done,
        ap_idle => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_idle,
        ap_ready => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        buffer_31_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out,
        buffer_31_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out_ap_vld,
        buffer_30_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out,
        buffer_30_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out_ap_vld,
        buffer_29_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out,
        buffer_29_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out_ap_vld,
        buffer_28_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out,
        buffer_28_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out_ap_vld,
        buffer_27_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out,
        buffer_27_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out_ap_vld,
        buffer_26_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out,
        buffer_26_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out_ap_vld,
        buffer_25_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out,
        buffer_25_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out_ap_vld,
        buffer_24_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out,
        buffer_24_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out_ap_vld,
        buffer_23_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out,
        buffer_23_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out_ap_vld,
        buffer_22_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out,
        buffer_22_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out_ap_vld,
        buffer_21_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out,
        buffer_21_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out_ap_vld,
        buffer_20_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out,
        buffer_20_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out_ap_vld,
        buffer_19_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out,
        buffer_19_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out_ap_vld,
        buffer_18_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out,
        buffer_18_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out_ap_vld,
        buffer_17_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out,
        buffer_17_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out_ap_vld,
        buffer_16_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out,
        buffer_16_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out_ap_vld,
        buffer_15_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out,
        buffer_15_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out_ap_vld,
        buffer_14_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out,
        buffer_14_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out_ap_vld,
        buffer_13_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out,
        buffer_13_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out_ap_vld,
        buffer_12_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out,
        buffer_12_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out_ap_vld,
        buffer_11_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out,
        buffer_11_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out_ap_vld,
        buffer_10_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out,
        buffer_10_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out_ap_vld,
        buffer_9_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out,
        buffer_9_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out_ap_vld,
        buffer_8_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out,
        buffer_8_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out_ap_vld,
        buffer_7_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out,
        buffer_7_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out_ap_vld,
        buffer_6_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out,
        buffer_6_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out_ap_vld,
        buffer_5_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out,
        buffer_5_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out_ap_vld,
        buffer_4_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out,
        buffer_4_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out_ap_vld,
        buffer_3_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out,
        buffer_3_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out_ap_vld,
        buffer_2_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out,
        buffer_2_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out_ap_vld,
        buffer_1_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out,
        buffer_1_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out_ap_vld,
        buffer_out => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out,
        buffer_out_ap_vld => grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out_ap_vld);

    control_s_axi_U : component pack_int4_transpose_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        num_elements => num_elements,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_in_stream_V_data_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv16_FFFF,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TSTRB_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component pack_int4_transpose_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => p_out_last_reg_782,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln23_fu_369_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_ready = ap_const_logic_1)) then 
                    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_98 <= ap_const_lv27_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln23_fu_369_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                i_fu_98 <= i_2_fu_374_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                num_blocks_reg_769 <= num_blocks_fu_349_p3;
                sub_reg_774 <= sub_fu_356_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_out_last_reg_782 <= p_out_last_fu_380_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_1_reg_759 <= sub_ln21_fu_306_p2(31 downto 5);
                tmp_2_reg_764 <= num_elements(31 downto 5);
                tmp_reg_754 <= num_elements(31 downto 31);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state3, grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln23_fu_369_p2, ap_CS_fsm_state4, out_stream_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln23_fu_369_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln23_fu_369_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done)
    begin
        if ((grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
        if ((out_stream_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
        if ((out_stream_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state3, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln23_fu_369_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln23_fu_369_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln23_fu_369_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln23_fu_369_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start <= grp_pack_int4_transpose_Pipeline_read_loop_fu_254_ap_start_reg;
    i_2_fu_374_p2 <= std_logic_vector(unsigned(i_fu_98) + unsigned(ap_const_lv27_1));
    icmp_ln23_fu_369_p2 <= "1" when (signed(zext_ln23_fu_365_p1) < signed(num_blocks_reg_769)) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_pack_int4_transpose_Pipeline_read_loop_fu_254_in_stream_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_stream_TREADY_int_regslice <= grp_pack_int4_transpose_Pipeline_read_loop_fu_254_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    num_blocks_fu_349_p3 <= 
        sub_ln21_1_fu_340_p2 when (tmp_reg_754(0) = '1') else 
        zext_ln21_1_fu_346_p1;

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= (((((((((((((((((((((((((((((((grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_31_out & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_27_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_23_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_19_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_15_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_11_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_7_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_3_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_30_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_26_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_22_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_18_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_14_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_10_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_6_out) 
    & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_2_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_29_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_25_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_21_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_17_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_13_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_9_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_5_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_1_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_28_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_24_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_20_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_16_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_12_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_8_out) & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_4_out) 
    & grp_pack_int4_transpose_Pipeline_read_loop_fu_254_buffer_out);
    out_stream_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXX";
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state5, out_stream_TREADY_int_regslice)
    begin
        if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_out_last_fu_380_p2 <= "1" when (zext_ln23_fu_365_p1 = sub_reg_774) else "0";
    sub_fu_356_p2 <= std_logic_vector(unsigned(num_blocks_fu_349_p3) + unsigned(ap_const_lv28_FFFFFFF));
    sub_ln21_1_fu_340_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(zext_ln21_fu_337_p1));
    sub_ln21_fu_306_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(num_elements));
    zext_ln21_1_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_764),28));
    zext_ln21_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_759),28));
    zext_ln23_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_98),28));
end behav;
