-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kv_page_ops is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    cmd_stream_TVALID : IN STD_LOGIC;
    resp_stream_TREADY : IN STD_LOGIC;
    cmd_stream_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    cmd_stream_TREADY : OUT STD_LOGIC;
    cmd_stream_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    cmd_stream_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    cmd_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    resp_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    resp_stream_TVALID : OUT STD_LOGIC;
    resp_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    resp_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    resp_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of kv_page_ops is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "kv_page_ops_kv_page_ops,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.743000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=236,HLS_SYN_LUT=351,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal icmp_ln54_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal op_reg_315 : STD_LOGIC_VECTOR (7 downto 0);
    signal op_reg_315_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_resp_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal op_reg_315_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal num_cmds : STD_LOGIC_VECTOR (31 downto 0);
    signal kv_memory_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal kv_memory_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal kv_memory_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmd_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal resp_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_predicate_pred128_state3 : BOOLEAN;
    signal ap_predicate_pred55_state4 : BOOLEAN;
    signal op_fu_227_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_reg_319 : STD_LOGIC_VECTOR (31 downto 0);
    signal phys_addr_fu_277_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal phys_addr_reg_324 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln78_reg_331 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln79_fu_288_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_fu_292_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_118 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln54_fu_217_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal kv_memory_ce0_local : STD_LOGIC;
    signal kv_memory_we1_local : STD_LOGIC;
    signal kv_memory_ce1_local : STD_LOGIC;
    signal grp_fu_184_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_cast_fu_207_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_251_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_261_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal offset_fu_231_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln70_fu_269_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln70_1_fu_273_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal regslice_both_cmd_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal cmd_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal cmd_stream_TVALID_int_regslice : STD_LOGIC;
    signal cmd_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_cmd_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_cmd_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal cmd_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_cmd_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_cmd_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_cmd_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal cmd_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_cmd_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_cmd_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_cmd_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal cmd_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_cmd_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_cmd_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal resp_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal resp_stream_TVALID_int_regslice : STD_LOGIC;
    signal resp_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_resp_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_resp_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_resp_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_resp_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_resp_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal resp_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_resp_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_resp_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_resp_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_resp_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_resp_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_condition_212 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component kv_page_ops_kv_memory_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component kv_page_ops_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        num_cmds : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component kv_page_ops_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component kv_page_ops_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    kv_memory_U : component kv_page_ops_kv_memory_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8192,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => kv_memory_address0,
        ce0 => kv_memory_ce0_local,
        q0 => kv_memory_q0,
        address1 => kv_memory_address1,
        ce1 => kv_memory_ce1_local,
        we1 => kv_memory_we1_local,
        d1 => data_in_reg_319);

    control_s_axi_U : component kv_page_ops_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        num_cmds => num_cmds,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    flow_control_loop_pipe_U : component kv_page_ops_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);

    regslice_both_cmd_stream_V_data_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => cmd_stream_TDATA,
        vld_in => cmd_stream_TVALID,
        ack_in => regslice_both_cmd_stream_V_data_V_U_ack_in,
        data_out => cmd_stream_TDATA_int_regslice,
        vld_out => cmd_stream_TVALID_int_regslice,
        ack_out => cmd_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_cmd_stream_V_data_V_U_apdone_blk);

    regslice_both_cmd_stream_V_keep_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => cmd_stream_TKEEP,
        vld_in => cmd_stream_TVALID,
        ack_in => regslice_both_cmd_stream_V_keep_V_U_ack_in,
        data_out => cmd_stream_TKEEP_int_regslice,
        vld_out => regslice_both_cmd_stream_V_keep_V_U_vld_out,
        ack_out => cmd_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_cmd_stream_V_keep_V_U_apdone_blk);

    regslice_both_cmd_stream_V_strb_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => cmd_stream_TSTRB,
        vld_in => cmd_stream_TVALID,
        ack_in => regslice_both_cmd_stream_V_strb_V_U_ack_in,
        data_out => cmd_stream_TSTRB_int_regslice,
        vld_out => regslice_both_cmd_stream_V_strb_V_U_vld_out,
        ack_out => cmd_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_cmd_stream_V_strb_V_U_apdone_blk);

    regslice_both_cmd_stream_V_last_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => cmd_stream_TLAST,
        vld_in => cmd_stream_TVALID,
        ack_in => regslice_both_cmd_stream_V_last_V_U_ack_in,
        data_out => cmd_stream_TLAST_int_regslice,
        vld_out => regslice_both_cmd_stream_V_last_V_U_vld_out,
        ack_out => cmd_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_cmd_stream_V_last_V_U_apdone_blk);

    regslice_both_resp_stream_V_data_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => resp_stream_TDATA_int_regslice,
        vld_in => resp_stream_TVALID_int_regslice,
        ack_in => resp_stream_TREADY_int_regslice,
        data_out => resp_stream_TDATA,
        vld_out => regslice_both_resp_stream_V_data_V_U_vld_out,
        ack_out => resp_stream_TREADY,
        apdone_blk => regslice_both_resp_stream_V_data_V_U_apdone_blk);

    regslice_both_resp_stream_V_keep_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => resp_stream_TVALID_int_regslice,
        ack_in => regslice_both_resp_stream_V_keep_V_U_ack_in_dummy,
        data_out => resp_stream_TKEEP,
        vld_out => regslice_both_resp_stream_V_keep_V_U_vld_out,
        ack_out => resp_stream_TREADY,
        apdone_blk => regslice_both_resp_stream_V_keep_V_U_apdone_blk);

    regslice_both_resp_stream_V_strb_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => resp_stream_TSTRB_int_regslice,
        vld_in => resp_stream_TVALID_int_regslice,
        ack_in => regslice_both_resp_stream_V_strb_V_U_ack_in_dummy,
        data_out => resp_stream_TSTRB,
        vld_out => regslice_both_resp_stream_V_strb_V_U_vld_out,
        ack_out => resp_stream_TREADY,
        apdone_blk => regslice_both_resp_stream_V_strb_V_U_apdone_blk);

    regslice_both_resp_stream_V_last_V_U : component kv_page_ops_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => resp_stream_TVALID_int_regslice,
        ack_in => regslice_both_resp_stream_V_last_V_U_ack_in_dummy,
        data_out => resp_stream_TLAST,
        vld_out => regslice_both_resp_stream_V_last_V_U_vld_out,
        ack_out => resp_stream_TREADY,
        apdone_blk => regslice_both_resp_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_212)) then
                if ((icmp_ln54_fu_211_p2 = ap_const_lv1_1)) then 
                    i_fu_118 <= add_ln54_fu_217_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_118 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    ap_predicate_pred128_state3 <= (op_reg_315 = ap_const_lv8_0);
                data_in_reg_319 <= cmd_stream_TDATA_int_regslice(63 downto 32);
                op_reg_315 <= op_fu_227_p1;
                op_reg_315_pp0_iter1_reg <= op_reg_315;
                phys_addr_reg_324 <= phys_addr_fu_277_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    ap_predicate_pred55_state4 <= (op_reg_315_pp0_iter1_reg = ap_const_lv8_0);
                op_reg_315_pp0_iter2_reg <= op_reg_315_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln78_reg_331 <= grp_fu_193_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln54_fu_217_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state1_pp0_stage0_iter0, regslice_both_resp_stream_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3, ap_loop_exit_ready_pp0_iter2_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_resp_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state1_pp0_stage0_iter0, regslice_both_resp_stream_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_block_state4_pp0_stage0_iter3, ap_block_state4_io, ap_loop_exit_ready_pp0_iter2_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_resp_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state1_pp0_stage0_iter0, regslice_both_resp_stream_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_block_state4_pp0_stage0_iter3, ap_block_state4_io, ap_loop_exit_ready_pp0_iter2_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_resp_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(icmp_ln54_fu_211_p2, cmd_stream_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln54_fu_211_p2 = ap_const_lv1_1) and (cmd_stream_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(op_reg_315_pp0_iter1_reg, resp_stream_TREADY_int_regslice)
    begin
                ap_block_state3_io <= ((op_reg_315_pp0_iter1_reg = ap_const_lv8_0) and (resp_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(op_reg_315_pp0_iter1_reg, regslice_both_resp_stream_V_data_V_U_apdone_blk, resp_stream_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((regslice_both_resp_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or ((op_reg_315_pp0_iter1_reg = ap_const_lv8_0) and (resp_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state4_io_assign_proc : process(op_reg_315_pp0_iter2_reg, resp_stream_TREADY_int_regslice)
    begin
                ap_block_state4_io <= ((op_reg_315_pp0_iter2_reg = ap_const_lv8_0) and (resp_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(op_reg_315_pp0_iter2_reg, resp_stream_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage0_iter3 <= ((op_reg_315_pp0_iter2_reg = ap_const_lv8_0) and (resp_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_212_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_212 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln54_fu_211_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln54_fu_211_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_loop_exit_ready_pp0_iter2_reg, ap_block_pp0_stage0_subdone, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_118, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_118;
        end if; 
    end process;


    cmd_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln54_fu_211_p2, ap_block_pp0_stage0, ap_start_int, cmd_stream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln54_fu_211_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cmd_stream_TDATA_blk_n <= cmd_stream_TVALID_int_regslice;
        else 
            cmd_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    cmd_stream_TREADY <= regslice_both_cmd_stream_V_data_V_U_ack_in;

    cmd_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln54_fu_211_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln54_fu_211_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cmd_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            cmd_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_184_p4 <= phys_addr_reg_324(16 downto 13);
    grp_fu_193_p2 <= "1" when (grp_fu_184_p4 = ap_const_lv4_0) else "0";
    i_cast_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_load),32));
    icmp_ln54_fu_211_p2 <= "1" when (signed(i_cast_fu_207_p1) < signed(num_cmds)) else "0";
    kv_memory_address0 <= zext_ln79_fu_288_p1(13 - 1 downto 0);
    kv_memory_address1 <= zext_ln74_fu_292_p1(13 - 1 downto 0);

    kv_memory_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            kv_memory_ce0_local <= ap_const_logic_1;
        else 
            kv_memory_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    kv_memory_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            kv_memory_ce1_local <= ap_const_logic_1;
        else 
            kv_memory_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    kv_memory_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, op_reg_315, ap_block_pp0_stage0_11001, grp_fu_193_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (op_reg_315 = ap_const_lv8_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (grp_fu_193_p2 = ap_const_lv1_1))) then 
            kv_memory_we1_local <= ap_const_logic_1;
        else 
            kv_memory_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    offset_fu_231_p4 <= cmd_stream_TDATA_int_regslice(31 downto 16);
    op_fu_227_p1 <= cmd_stream_TDATA_int_regslice(8 - 1 downto 0);
    phys_addr_fu_277_p2 <= std_logic_vector(unsigned(zext_ln70_fu_269_p1) + unsigned(zext_ln70_1_fu_273_p1));

    resp_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, ap_predicate_pred128_state3, ap_predicate_pred55_state4, resp_stream_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_predicate_pred55_state4 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_pred128_state3 = ap_const_boolean_1)))) then 
            resp_stream_TDATA_blk_n <= resp_stream_TREADY_int_regslice;
        else 
            resp_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    resp_stream_TDATA_int_regslice <= 
        kv_memory_q0 when (icmp_ln78_reg_331(0) = '1') else 
        ap_const_lv32_0;
    resp_stream_TSTRB_int_regslice <= "XXXX";
    resp_stream_TVALID <= regslice_both_resp_stream_V_data_V_U_vld_out;

    resp_stream_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred128_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_pred128_state3 = ap_const_boolean_1))) then 
            resp_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            resp_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln_fu_261_p3 <= (tmp_fu_251_p4 & ap_const_lv7_0);
    tmp_fu_251_p4 <= cmd_stream_TDATA_int_regslice(13 downto 8);
    zext_ln70_1_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_fu_231_p4),17));
    zext_ln70_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_261_p3),17));
    zext_ln74_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(phys_addr_reg_324),64));
    zext_ln79_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(phys_addr_reg_324),64));
end behav;
